### ISSUE TITLE
Added gameplay

### ISSUE THREAD

**Issue by jtdwyer93** [ASU-CompMethodsPhysics-PHY494/final-card-counting-simulation#3]
Hey guys (@rhheilma and @lnbradsh),

I added blackjack gameplay, but for some reason some weird  <<<<HEAD message popped up in the blackjacktools.py file I uploaded. If you could check to see if the file runs for you guys, that would be cool. I saved a backup of the entire file if it is corrupted though, so no worries if it is broken. I tested it before I pushed it, so I know it is working.

I don't think my local files pulled the dealer commit that was pushed earlier though.

Thanks,

Jacob Dwyer

**Comment by orbeckst** [comment]
The `<<<<HEAD` means that someone forgot to properly merge. See links at [10_Git_for_collaboration](http://asu-compmethodsphysics-phy494.github.io/ASU-PHY494/2016/03/03/10_Git_for_collaboration/) on hints for merging.
