### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by rhheilma** [ASU-CompMethodsPhysics-PHY494/final-card-counting-simulation#9]
@jtdwyer93 @lnbradsh 

What font are we going to use???

**Comment by lnbradsh** [comment]
Does Dr. Beckstein recommend a certain font. If so, I'm ok with just his
recommendation.

**Comment by rhheilma** [comment]
He gives us a few options, Arial is one. I already started in that if that makes a difference.

**Comment by lnbradsh** [comment]
Arial works with me
